# Generated by Django 3.0.5 on 2021-07-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210627_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Ad', 'Admin'), ('Mod', 'Moderator')], default='Customer', max_length=10),
        ),
    ]
